spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sf_prod
    username: sf_prod_user
    password: Gieksa10

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false